apiVersion: v1
kind: Service
metadata:
  name: { { PROJECT_NAME } }
spec:
  selector:
    app: { { PROJECT_NAME } }
  ports:
    - protocol: TCP
      port: 80
      targetPort: { { APP_PORT } }
  type: ClusterIP
